name: Backend CI

on:
  pull_request:
    branches:
      - dev-be
    paths:
      - 'backend/**'

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Grant execute permission to gradlew
      run: chmod +x backend/gradlew

    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew build

    - name: Run tests
      run: |
        cd backend
        ./gradlew test
